#
#  Copyright (c) 2021-2025 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
#  SPDX-License-Identifier: Apache-2.0
#

module OSDP
  module LibFlag
    ENFORCE_SECURE = Sys::FLAG_ENFORCE_SECURE
    INSTALL_MODE = Sys::FLAG_INSTALL_MODE
    IGNORE_UNSOLICITED = Sys::FLAG_IGN_UNSOLICITED
    ENABLE_NOTIFICATION = Sys::FLAG_ENABLE_NOTIFICATION
    CAPTURE_PACKETS = Sys::FLAG_CAPTURE_PACKETS
    ALLOW_EMPTY_ENCRYPTED_DATA_BLOCK = Sys::FLAG_ALLOW_EMPTY_ENCRYPTED_DATA_BLOCK
  end

  module LogLevel
    EMERGENCY = Sys::LOG_EMERG
    ALERT = Sys::LOG_ALERT
    CRITICAL = Sys::LOG_CRIT
    ERROR = Sys::LOG_ERROR
    WARNING = Sys::LOG_WARNING
    NOTICE = Sys::LOG_NOTICE
    INFO = Sys::LOG_INFO
    DEBUG = Sys::LOG_DEBUG
  end

  module StatusReportType
    LOCAL = Sys::STATUS_REPORT_LOCAL
    INPUT = Sys::STATUS_REPORT_INPUT
    OUTPUT = Sys::STATUS_REPORT_OUTPUT
    REMOTE = Sys::STATUS_REPORT_REMOTE
  end

  module Command
    OUTPUT = Sys::CMD_OUTPUT
    BUZZER = Sys::CMD_BUZZER
    LED = Sys::CMD_LED
    COMSET = Sys::CMD_COMSET
    COMSET_DONE = Sys::CMD_COMSET_DONE
    TEXT = Sys::CMD_TEXT
    MANUFACTURER = Sys::CMD_MFG
    KEYSET = Sys::CMD_KEYSET
    FILE_TRANSFER = Sys::CMD_FILE_TX
    STATUS = Sys::CMD_STATUS
  end

  module CommandLEDColor
    BLACK = Sys::LED_COLOR_NONE
    RED = Sys::LED_COLOR_RED
    GREEN = Sys::LED_COLOR_GREEN
    AMBER = Sys::LED_COLOR_AMBER
    BLUE = Sys::LED_COLOR_BLUE
    MAGENTA = Sys::LED_COLOR_MAGENTA
    CYAN = Sys::LED_COLOR_CYAN
    WHITE = Sys::LED_COLOR_WHITE
  end

  module CommandFileTxFlags
    CANCEL = Sys::CMD_FILE_TX_FLAG_CANCEL
  end

  module EventNotification
    COMMAND = Sys::EVENT_NOTIFICATION_COMMAND
    SECURE_CHANNEL_STATUS = Sys::EVENT_NOTIFICATION_SC_STATUS
    PERIPHERAL_DEVICE_STATUS = Sys::EVENT_NOTIFICATION_PD_STATUS
  end

  module Event
    CARD_READ = Sys::EVENT_CARDREAD
    KEY_PRESS = Sys::EVENT_KEYPRESS
    MANUFACTURER_REPLY = Sys::EVENT_MFGREP
    STATUS = Sys::EVENT_STATUS
    NOTIFICATION = Sys::EVENT_NOTIFICATION
  end

  module CardFormat
    UNSPECIFIED = Sys::CARD_FMT_RAW_UNSPECIFIED
    WIEGAND = Sys::CARD_FMT_RAW_WIEGAND
    ASCII = Sys::CARD_FMT_ASCII
  end

  module Capability
    UNUSED = Sys::CAP_UNUSED
    CONTACT_STATUS_MONITORING = Sys::CAP_CONTACT_STATUS_MONITORING
    OUTPUT_CONTROL = Sys::CAP_OUTPUT_CONTROL
    CARD_DATA_FORMAT = Sys::CAP_CARD_DATA_FORMAT
    LED_CONTROL = Sys::CAP_READER_LED_CONTROL
    AUDIBLE_CONTROL = Sys::CAP_READER_AUDIBLE_OUTPUT
    TEXT_OUTPUT = Sys::CAP_READER_TEXT_OUTPUT
    TIME_KEEPING = Sys::CAP_TIME_KEEPING
    CHECK_CHARACTER = Sys::CAP_CHECK_CHARACTER_SUPPORT
    COMMUNICATION_SECURITY = Sys::CAP_COMMUNICATION_SECURITY
    RECEIVE_BUFFER_SIZE = Sys::CAP_RECEIVE_BUFFERSIZE
    COMBINED_MESSAGE_SIZE = Sys::CAP_LARGEST_COMBINED_MESSAGE_SIZE
    SMART_CARD = Sys::CAP_SMART_CARD_SUPPORT
    READERS = Sys::CAP_READERS
    BIOMETRICS = Sys::CAP_BIOMETRICS
  end
end
